name: Build and Sign iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9' # 可以根据需要选择特定的 Flutter 版本

      - name: Verify Flutter environment variables
        run: |
          echo "FLUTTER_ROOT: $FLUTTER_ROOT"
          echo "PATH: $PATH"
          flutter --version

      - name: Build and Archive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath ./build/Runner.xcarchive -allowProvisioningUpdates

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath ./build/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build -allowProvisioningUpdates

      - name: Upload IPA to Artifact Storage
        uses: actions/upload-artifact@v2
        with:
          name: AppIPA
          path: ./build/*.ipa